### ISSUE TITLE
[Question] Can I use Vita as State Container, if so can I partition state/sharedViewModel?

### ISSUE THREAD

**Issue by dnhyde** [FarshadTahmasbi/Vita#4]
Hi,
Vita is defined as a lib to share ViewModels across activity or make them global at App level.
But can it be used a state container / single source of truth for Android? Quoting web frameworks (sorry for that) can Vita be the [Redux](https://redux.js.org/)/[Vuex](https://vuex.vuejs.org/) for Android ecosystem?

More specifically: in case of a ViewModel with **No Owner** (shared across all application) is there a way to lazy load only the parts of the ViewModel that are needed at a certain point to avoid fat ViewModel?

You could say just use a regular ViewModel for that fragment/activity, but what if I need the same ViewModel with te same info (e.g. the logged user and I do not want to use sharedPrefs) at different places in my app? Is it possible to modularize the ViewModel with **No Owner** and load only chunks of it when needed?

Thanks!

**Comment by FarshadTahmasbi** [comment]
Dear Daniele, As you noticed the idea behind vita is sharing `ViewModel`s everywhere! it's simply a singleton which is responsible for `ViewModelStore`s and their lifecycle, The purpose is to bind data to components' lifecycle as google did, no more! 
**No Owner** type stays alive while at least one owner is alive, in case you need to share data all over the app and also need to release it on app close, it is a good choice, but in your case (Apparently you don't want to use persist data like prefs) maybe you should try something else like a memory cache in app level.
Regards, Farshad
